In [3]:
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine, text

load_dotenv("../.env")

engine = create_engine(
    f"mysql+pymysql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}"
    f"@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}"
)

with engine.connect() as conn:
    print(conn.execute(text("SELECT 1")).fetchone())

(1,)

In [4]:
import os
from dotenv import load_dotenv

load_dotenv("../.env", override=True)

API_KEY = os.getenv("MOLIT_API_KEY")

print("API KEY 로드:", API_KEY is not None)

API KEY 로드: True

In [11]:
import xml.etree.ElementTree as ET
import pandas as pd

root = ET.fromstring(response.text)

rows = []

for item in root.findall(".//item"):
    rows.append({
        child.tag: child.text
        for child in item
    })

df = pd.DataFrame(rows)

print(df.shape)
display(df.head())

(10, 25)

,aptNm,aptSeq,buildYear,contractTerm,contractType,dealDay,dealMonth,dealYear,deposit,excluUseAr,...,roadnm,roadnmbcd,roadnmbonbun,roadnmbubun,roadnmcd,roadnmseq,roadnmsggcd,sggCd,umdNm,useRRRight
0,은마,11680-218,1979,,,18,1,2024,"20,000",84.43,...,삼성로 212,0,00212,00000,3122005,4,11680,11680,대치동,
1,대치SKVIEW,11680-4637,2017,,,22,1,2024,"140,000",112.3685,...,삼성로51길 25,0,00025,00000,4166413,1,11680,11680,대치동,
2,한보미도맨션1,11680-222,1983,,,11,1,2024,"70,000",128.01,...,삼성로 150,0,00150,00000,3122005,4,11680,11680,대치동,
3,신동아,11680-319,1992,,,10,1,2024,"33,000",39.53,...,광평로47길 17,0,00017,00000,4166080,1,11680,11680,수서동,
4,수서한아름,11680-318,1993,,,27,1,2024,"110,000",163.68,...,광평로51길 22,0,00022,00000,4166081,1,11680,11680,수서동,

In [12]:
print(df.shape)
print(df.columns.tolist())

(10, 25)
['aptNm', 'aptSeq', 'buildYear', 'contractTerm', 'contractType', 'dealDay', 'dealMonth', 'dealYear', 'deposit', 'excluUseAr', 'floor', 'jibun', 'monthlyRent', 'preDeposit', 'preMonthlyRent', 'roadnm', 'roadnmbcd', 'roadnmbonbun', 'roadnmbubun', 'roadnmcd', 'roadnmseq', 'roadnmsggcd', 'sggCd', 'umdNm', 'useRRRight']

In [13]:
url = (
    "https://apis.data.go.kr/1613000/RTMSDataSvcAptRent/getRTMSDataSvcAptRent"
    f"?serviceKey={API_KEY}"
    "&LAWD_CD=11680"
    "&DEAL_YMD=202401"
    "&numOfRows=1000"
    "&pageNo=1"
)

response = requests.get(url)

print(response.status_code)

200

In [14]:
print(df.shape)

(10, 25)

In [15]:
import requests
import xml.etree.ElementTree as ET
import pandas as pd

url = (
    "https://apis.data.go.kr/1613000/RTMSDataSvcAptRent/getRTMSDataSvcAptRent"
    f"?serviceKey={API_KEY}"
    "&LAWD_CD=11680"
    "&DEAL_YMD=202401"
    "&numOfRows=1000"
    "&pageNo=1"
)

response = requests.get(url)

root = ET.fromstring(response.text)

rows = []
for item in root.findall(".//item"):
    rows.append({child.tag: child.text for child in item})

df = pd.DataFrame(rows)

print(response.status_code)
print(df.shape)

200
(1000, 25)

In [16]:
total_count = root.findtext(".//totalCount")
print("전체 거래 건수:", total_count)

전체 거래 건수: 2464

In [17]:
url = (
    "https://apis.data.go.kr/1613000/RTMSDataSvcAptRent/getRTMSDataSvcAptRent"
    f"?serviceKey={API_KEY}"
    "&LAWD_CD=11680"
    "&DEAL_YMD=202401"
    "&numOfRows=3000"
    "&pageNo=1"
)

response = requests.get(url)

root = ET.fromstring(response.text)

rows = []
for item in root.findall(".//item"):
    rows.append({child.tag: child.text for child in item})

df = pd.DataFrame(rows)

print(df.shape)

(2464, 25)

In [18]:
df.to_csv(
    "../data/raw/gangnam_rent_202401.csv",
    index=False,
    encoding="utf-8-sig"
)

print("저장 완료")

저장 완료

In [19]:
df.isnull().sum()

aptNm               0
aptSeq              0
buildYear           0
contractTerm        0
contractType        0
dealDay             0
dealMonth           0
dealYear            0
deposit             0
excluUseAr          0
floor               0
jibun               0
monthlyRent         0
preDeposit          0
preMonthlyRent      0
roadnm              0
roadnmbcd         559
roadnmbonbun        0
roadnmbubun         0
roadnmcd            0
roadnmseq           0
roadnmsggcd         0
sggCd               0
umdNm               0
useRRRight          0
dtype: int64

In [20]:
df["deposit"] = (
    df["deposit"]
    .str.replace(",", "", regex=False)
    .astype(int)
)

df["monthlyRent"] = pd.to_numeric(df["monthlyRent"], errors="coerce")

print(df[["deposit", "monthlyRent"]].dtypes)
df[["deposit", "monthlyRent"]].head()

deposit        int64
monthlyRent    int64
dtype: object

   deposit  monthlyRent
0    20000          160
1   140000            0
2    70000          230
3    33000            0
4   110000            0

In [21]:
numeric_cols = [
    "excluUseAr",
    "floor",
    "buildYear",
    "dealYear",
    "dealMonth",
    "dealDay"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

print(df[numeric_cols].dtypes)

excluUseAr    float64
floor           int64
buildYear       int64
dealYear        int64
dealMonth       int64
dealDay         int64
dtype: object

In [22]:
df["dealDate"] = pd.to_datetime(
    df["dealYear"].astype(str) + "-" +
    df["dealMonth"].astype(str) + "-" +
    df["dealDay"].astype(str)
)

print(df["dealDate"].head())
print(df["dealDate"].dtype)

0   2024-01-18
1   2024-01-22
2   2024-01-11
3   2024-01-10
4   2024-01-27
Name: dealDate, dtype: datetime64[us]
datetime64[us]

In [23]:
df["rentType"] = df["monthlyRent"].apply(
    lambda x: "전세" if x == 0 else "월세"
)

print(df["rentType"].value_counts())

rentType
전세    1435
월세    1029
Name: count, dtype: int64

In [24]:
df.to_csv(
    "../data/processed/gangnam_rent_202401_clean.csv",
    index=False,
    encoding="utf-8-sig"
)

print(df.shape)
print("정제 데이터 저장 완료")

(2464, 27)
정제 데이터 저장 완료

In [2]:
import pandas as pd

df = pd.read_csv(
    "../data/processed/gangnam_rent_202401_clean.csv"
)

print(df.shape)

(2464, 27)

In [3]:
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine

load_dotenv("../.env", override=True)

engine = create_engine(
    f"mysql+pymysql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}"
    f"@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}"
)

print("MySQL 연결 준비 완료")

MySQL 연결 준비 완료

In [4]:
df.to_sql(
    name="rental_transactions",
    con=engine,
    if_exists="replace",
    index=False
)

print("MySQL 저장 완료")

MySQL 저장 완료

In [5]:
from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(
        text("SELECT COUNT(*) FROM rental_transactions")
    )
    print(result.fetchone())

(2464,)

In [6]:
query = """
SELECT
    rentType,
    COUNT(*) AS contract_count,
    ROUND(AVG(deposit), 0) AS avg_deposit,
    ROUND(AVG(monthlyRent), 0) AS avg_monthly_rent
FROM rental_transactions
GROUP BY rentType;
"""

result = pd.read_sql(query, engine)
result

  rentType  contract_count  avg_deposit  avg_monthly_rent
0       월세            1029      39061.0             188.0
1       전세            1435      84837.0               0.0

In [8]:
import os
from dotenv import load_dotenv

load_dotenv("../.env", override=True)

API_KEY = os.getenv("MOLIT_API_KEY")

print("API KEY 로드:", API_KEY is not None)

API KEY 로드: True

In [9]:
import requests
import xml.etree.ElementTree as ET
import pandas as pd
import time

all_rows = []

for month in range(1, 13):
    ymd = f"2024{month:02d}"

    url = (
        "https://apis.data.go.kr/1613000/RTMSDataSvcAptRent/getRTMSDataSvcAptRent"
        f"?serviceKey={API_KEY}"
        "&LAWD_CD=11680"
        f"&DEAL_YMD={ymd}"
        "&numOfRows=5000"
        "&pageNo=1"
    )

    response = requests.get(url)
    root = ET.fromstring(response.text)

    items = root.findall(".//item")

    for item in items:
        all_rows.append({
            child.tag: child.text
            for child in item
        })

    print(ymd, len(items), "건")

    time.sleep(0.2)

df_2024 = pd.DataFrame(all_rows)

print("전체:", df_2024.shape)

202401 2464 건
202402 1985 건
202403 1976 건
202404 1651 건
202405 2539 건
202406 2073 건
202407 1648 건
202408 1613 건
202409 1341 건
202410 1744 건
202411 1696 건
202412 2098 건
전체: (22828, 25)

In [10]:
df_2024.to_csv(
    "../data/raw/gangnam_rent_2024.csv",
    index=False,
    encoding="utf-8-sig"
)

print("저장 완료:", df_2024.shape)

저장 완료: (22828, 25)

In [11]:
df = df_2024.copy()

# 가격
df["deposit"] = df["deposit"].str.replace(",", "", regex=False).astype(int)
df["monthlyRent"] = pd.to_numeric(df["monthlyRent"], errors="coerce")

# 숫자형
numeric_cols = [
    "excluUseAr", "floor", "buildYear",
    "dealYear", "dealMonth", "dealDay"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# 거래일자
df["dealDate"] = pd.to_datetime(
    df["dealYear"].astype(str) + "-" +
    df["dealMonth"].astype(str) + "-" +
    df["dealDay"].astype(str)
)

# 전세/월세
df["rentType"] = df["monthlyRent"].apply(
    lambda x: "전세" if x == 0 else "월세"
)

print(df.shape)
print(df["rentType"].value_counts())

(22828, 27)
rentType
전세    12116
월세    10712
Name: count, dtype: int64

In [12]:
df.to_csv(
    "../data/processed/gangnam_rent_2024_clean.csv",
    index=False,
    encoding="utf-8-sig"
)

print("저장 완료:", df.shape)

저장 완료: (22828, 27)

In [13]:
df.to_sql(
    name="rental_transactions",
    con=engine,
    if_exists="replace",
    index=False
)

print("MySQL 저장 완료:", len(df))

MySQL 저장 완료: 22828

In [14]:
query = """
SELECT
    dealMonth,
    COUNT(*) AS contract_count
FROM rental_transactions
GROUP BY dealMonth
ORDER BY dealMonth;
"""

monthly = pd.read_sql(query, engine)
monthly

    dealMonth  contract_count
0           1            2464
1           2            1985
2           3            1976
3           4            1651
4           5            2539
5           6            2073
6           7            1648
7           8            1613
8           9            1341
9          10            1744
10         11            1696
11         12            2098

In [15]:
seoul_gu = {
    "종로구": "11110",
    "중구": "11140",
    "용산구": "11170",
    "성동구": "11200",
    "광진구": "11215",
    "동대문구": "11230",
    "중랑구": "11260",
    "성북구": "11290",
    "강북구": "11305",
    "도봉구": "11320",
    "노원구": "11350",
    "은평구": "11380",
    "서대문구": "11410",
    "마포구": "11440",
    "양천구": "11470",
    "강서구": "11500",
    "구로구": "11530",
    "금천구": "11545",
    "영등포구": "11560",
    "동작구": "11590",
    "관악구": "11620",
    "서초구": "11650",
    "강남구": "11680",
    "송파구": "11710",
    "강동구": "11740"
}

print(len(seoul_gu))

25

In [16]:
all_rows = []

for gu_name, gu_code in seoul_gu.items():
    for month in range(1, 13):
        ymd = f"2024{month:02d}"

        url = (
            "https://apis.data.go.kr/1613000/RTMSDataSvcAptRent/getRTMSDataSvcAptRent"
            f"?serviceKey={API_KEY}"
            f"&LAWD_CD={gu_code}"
            f"&DEAL_YMD={ymd}"
            "&numOfRows=5000"
            "&pageNo=1"
        )

        response = requests.get(url)
        root = ET.fromstring(response.text)
        items = root.findall(".//item")

        for item in items:
            row = {child.tag: child.text for child in item}
            row["guName"] = gu_name
            all_rows.append(row)

        print(gu_name, ymd, len(items))

        time.sleep(0.2)

df_seoul_2024 = pd.DataFrame(all_rows)

print("전체:", df_seoul_2024.shape)

종로구 202401 234
종로구 202402 173
종로구 202403 185
종로구 202404 134
종로구 202405 167
종로구 202406 151
종로구 202407 160
종로구 202408 143
종로구 202409 120
종로구 202410 147
종로구 202411 162
종로구 202412 239
중구 202401 398
중구 202402 372
중구 202403 373
중구 202404 309
중구 202405 324
중구 202406 270
중구 202407 329
중구 202408 269
중구 202409 255
중구 202410 302
중구 202411 253
중구 202412 298
용산구 202401 563
용산구 202402 503
용산구 202403 553
용산구 202404 709
용산구 202405 631
용산구 202406 586
용산구 202407 391
용산구 202408 464
용산구 202409 377
용산구 202410 470
용산구 202411 724
용산구 202412 662
성동구 202401 966
성동구 202402 844
성동구 202403 951
성동구 202404 778
성동구 202405 761
성동구 202406 771
성동구 202407 757
성동구 202408 762
성동구 202409 655
성동구 202410 791
성동구 202411 731
성동구 202412 863
광진구 202401 420
광진구 202402 388
광진구 202403 410
광진구 202404 326
광진구 202405 337
광진구 202406 343
광진구 202407 338
광진구 202408 360
광진구 202409 310
광진구 202410 377
광진구 202411 372
광진구 202412 498
동대문구 202401 818
동대문구 202402 701
동대문구 202403 769
동대문구 202404 584
동대문구 202405 651
동대문구 202406 606
동대문구 202407 700
동대문구 202408 648
동대문구 202409 515
동대문구 202410 778
동대문구 202411 700
동대문구 202412 1023
중랑구 202401 685
중랑구 202402 869
중랑구 202403 825
중랑구 202404 559
중랑구 202405 555
중랑구 202406 630
중랑구 202407 570
중랑구 202408 788
중랑구 202409 502
중랑구 202410 403
중랑구 202411 465
중랑구 202412 418
성북구 202401 878
성북구 202402 774
성북구 202403 1153
성북구 202404 625
성북구 202405 789
성북구 202406 715
성북구 202407 758
성북구 202408 672
성북구 202409 581
성북구 202410 707
성북구 202411 706
성북구 202412 778
강북구 202401 290
강북구 202402 282
강북구 202403 321
강북구 202404 257
강북구 202405 294
강북구 202406 257
강북구 202407 310
강북구 202408 266
강북구 202409 226
강북구 202410 246
강북구 202411 204
강북구 202412 272
도봉구 202401 617
도봉구 202402 533
도봉구 202403 624
도봉구 202404 508
도봉구 202405 504
도봉구 202406 492
도봉구 202407 499
도봉구 202408 489
도봉구 202409 425
도봉구 202410 501
도봉구 202411 458
도봉구 202412 403
노원구 202401 1852
노원구 202402 1667
노원구 202403 1875
노원구 202404 1598
노원구 202405 1728
노원구 202406 1402
노원구 202407 1496
노원구 202408 1430
노원구 202409 1247
노원구 202410 1504
노원구 202411 1410
노원구 202412 1513
은평구 202401 730
은평구 202402 767
은평구 202403 1044
은평구 202404 884
은평구 202405 1004
은평구 202406 792
은평구 202407 811
은평구 202408 708
은평구 202409 868
은평구 202410 764
은평구 202411 925
은평구 202412 761
서대문구 202401 753
서대문구 202402 823
서대문구 202403 609
서대문구 202404 535
서대문구 202405 538
서대문구 202406 517
서대문구 202407 715
서대문구 202408 560
서대문구 202409 533
서대문구 202410 627
서대문구 202411 615
서대문구 202412 733
마포구 202401 1137
마포구 202402 1023
마포구 202403 1232
마포구 202404 838
마포구 202405 982
마포구 202406 880
마포구 202407 835
마포구 202408 995
마포구 202409 885
마포구 202410 937
마포구 202411 892
마포구 202412 1151
양천구 202401 1027
양천구 202402 864
양천구 202403 1018
양천구 202404 899
양천구 202405 1047
양천구 202406 873
양천구 202407 992
양천구 202408 897
양천구 202409 699
양천구 202410 1048
양천구 202411 950
양천구 202412 981
강서구 202401 1358
강서구 202402 1089
강서구 202403 1354
강서구 202404 1107
강서구 202405 1233
강서구 202406 1131
강서구 202407 1678
강서구 202408 1859
강서구 202409 1021
강서구 202410 1347
강서구 202411 1375
강서구 202412 1059
구로구 202401 921
구로구 202402 884
구로구 202403 928
구로구 202404 927
구로구 202405 907
구로구 202406 836
구로구 202407 1097
구로구 202408 1033
구로구 202409 792
구로구 202410 778
구로구 202411 723
구로구 202412 819
금천구 202401 282
금천구 202402 303
금천구 202403 318
금천구 202404 281
금천구 202405 245
금천구 202406 191
금천구 202407 238
금천구 202408 228
금천구 202409 186
금천구 202410 238
금천구 202411 251
금천구 202412 257
영등포구 202401 1216
영등포구 202402 1003
영등포구 202403 1227
영등포구 202404 851
영등포구 202405 827
영등포구 202406 1356
영등포구 202407 1056
영등포구 202408 957
영등포구 202409 850
영등포구 202410 948
영등포구 202411 1204
영등포구 202412 999
동작구 202401 926
동작구 202402 717
동작구 202403 1037
동작구 202404 668
동작구 202405 707
동작구 202406 672
동작구 202407 700
동작구 202408 684
동작구 202409 668
동작구 202410 699
동작구 202411 744
동작구 202412 782
관악구 202401 603
관악구 202402 531
관악구 202403 596
관악구 202404 526
관악구 202405 533
관악구 202406 517
관악구 202407 579
관악구 202408 547
관악구 202409 485
관악구 202410 760
관악구 202411 530
관악구 202412 606
서초구 202401 1352
서초구 202402 1221
서초구 202403 1086
서초구 202404 1017
서초구 202405 1117
서초구 202406 1232
서초구 202407 1150
서초구 202408 1402
서초구 202409 1002
서초구 202410 1252
서초구 202411 1197
서초구 202412 1353
강남구 202401 2464
강남구 202402 1985
강남구 202403 1976
강남구 202404 1651
강남구 202405 2539
강남구 202406 2073
강남구 202407 1648
강남구 202408 1613
강남구 202409 1341
강남구 202410 1744
강남구 202411 1696
강남구 202412 2098
송파구 202401 2204
송파구 202402 1834
송파구 202403 2163
송파구 202404 1468
송파구 202405 1700
송파구 202406 1527
송파구 202407 1642
송파구 202408 1752
송파구 202409 1306
송파구 202410 1804
송파구 202411 1838
송파구 202412 2071
강동구 202401 1520
강동구 202402 1240
강동구 202403 1605
강동구 202404 1223
강동구 202405 1389
강동구 202406 1647
강동구 202407 1365
강동구 202408 1140
강동구 202409 987
강동구 202410 1341
강동구 202411 1373
강동구 202412 1876
전체: (252914, 26)

In [17]:
df_seoul_2024.to_csv(
    "../data/raw/seoul_rent_2024.csv",
    index=False,
    encoding="utf-8-sig"
)

print("저장 완료:", df_seoul_2024.shape)

저장 완료: (252914, 26)

In [18]:
df = df_seoul_2024.copy()

# 가격 숫자형 변환
df["deposit"] = (
    df["deposit"]
    .str.replace(",", "", regex=False)
    .astype(int)
)

df["monthlyRent"] = pd.to_numeric(df["monthlyRent"], errors="coerce")

# 기타 숫자형
numeric_cols = [
    "excluUseAr", "floor", "buildYear",
    "dealYear", "dealMonth", "dealDay"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# 거래일
df["dealDate"] = pd.to_datetime(
    df["dealYear"].astype(str) + "-" +
    df["dealMonth"].astype(str) + "-" +
    df["dealDay"].astype(str)
)

# 전세 / 월세
df["rentType"] = df["monthlyRent"].apply(
    lambda x: "전세" if x == 0 else "월세"
)

print(df.shape)
print(df["rentType"].value_counts())

(252914, 28)
rentType
전세    145224
월세    107690
Name: count, dtype: int64

In [19]:
df.to_csv(
    "../data/processed/seoul_rent_2024_clean.csv",
    index=False,
    encoding="utf-8-sig"
)

print("저장 완료:", df.shape)

저장 완료: (252914, 28)

In [20]:
df.to_sql(
    name="rental_transactions",
    con=engine,
    if_exists="replace",
    index=False,
    chunksize=5000
)

print("MySQL 저장 완료:", len(df))

MySQL 저장 완료: 252914

In [21]:
query = """
SELECT
    guName,
    COUNT(*) AS contract_count
FROM rental_transactions
GROUP BY guName
ORDER BY contract_count DESC;
"""

gu_count = pd.read_sql(query, engine)

print(gu_count)
print("구 개수:", len(gu_count))
print("전체:", gu_count["contract_count"].sum())

   guName  contract_count
0     강남구           22828
1     송파구           21309
2     노원구           18722
3     강동구           16706
4     강서구           15611
5     서초구           14381
6    영등포구           12494
7     마포구           11787
8     양천구           11295
9     구로구           10645
10    은평구           10058
11    성동구            9630
12    성북구            9136
13    동작구            9004
14   동대문구            8493
15   서대문구            7558
16    중랑구            7269
17    관악구            6813
18    용산구            6633
19    도봉구            6053
20    광진구            4479
21     중구            3752
22    강북구            3225
23    금천구            3018
24    종로구            2015
구 개수: 25
전체: 252914

In [22]:
kosis = pd.read_csv(
    "../data/raw/kosis_migration_2024.csv",
    encoding="utf-8"
)

print(kosis.shape)
print(kosis.columns.tolist())
kosis.head()

(26, 73)
['행정구역(시군구)별', '2024.01', '2024.01.1', '2024.01.2', '2024.01.3', '2024.01.4', '2024.01.5', '2024.02', '2024.02.1', '2024.02.2', '2024.02.3', '2024.02.4', '2024.02.5', '2024.03', '2024.03.1', '2024.03.2', '2024.03.3', '2024.03.4', '2024.03.5', '2024.04', '2024.04.1', '2024.04.2', '2024.04.3', '2024.04.4', '2024.04.5', '2024.05', '2024.05.1', '2024.05.2', '2024.05.3', '2024.05.4', '2024.05.5', '2024.06', '2024.06.1', '2024.06.2', '2024.06.3', '2024.06.4', '2024.06.5', '2024.07', '2024.07.1', '2024.07.2', '2024.07.3', '2024.07.4', '2024.07.5', '2024.08', '2024.08.1', '2024.08.2', '2024.08.3', '2024.08.4', '2024.08.5', '2024.09', '2024.09.1', '2024.09.2', '2024.09.3', '2024.09.4', '2024.09.5', '2024.10', '2024.10.1', '2024.10.2', '2024.10.3', '2024.10.4', '2024.10.5', '2024.11', '2024.11.1', '2024.11.2', '2024.11.3', '2024.11.4', '2024.11.5', '2024.12', '2024.12.1', '2024.12.2', '2024.12.3', '2024.12.4', '2024.12.5']

,행정구역(시군구)별,2024.01,2024.01.1,2024.01.2,2024.01.3,2024.01.4,2024.01.5,2024.02,2024.02.1,2024.02.2,...,2024.11.2,2024.11.3,2024.11.4,2024.11.5,2024.12,2024.12.1,2024.12.2,2024.12.3,2024.12.4,2024.12.5
0,행정구역(시군구)별,총전입 (명),총전출 (명),시도내이동-시군구간 전입 (명),시도내이동-시군구간 전출 (명),시도간전입 (명),시도간전출 (명),총전입 (명),총전출 (명),시도내이동-시군구간 전입 (명),...,시도내이동-시군구간 전입 (명),시도내이동-시군구간 전출 (명),시도간전입 (명),시도간전출 (명),총전입 (명),총전출 (명),시도내이동-시군구간 전입 (명),시도내이동-시군구간 전출 (명),시도간전입 (명),시도간전출 (명)
1,종로구,1725,1704,846,914,713,624,2356,2208,1082,...,631,769,428,414,1363,1581,695,842,490,561
2,중구,1587,1551,820,833,601,552,2050,1908,996,...,626,752,363,425,1315,1658,659,908,439,533
3,용산구,2638,3600,1079,1913,1019,1147,3067,3988,1307,...,891,1160,646,737,2222,2452,1029,1252,813,820
4,성동구,3147,3410,1519,1751,1178,1209,4202,4365,1886,...,1228,1635,692,932,2523,3151,1230,1737,830,951

In [23]:
kosis = pd.read_csv(
    "../data/raw/kosis_migration_2024.csv",
    encoding="utf-8",
    header=[0, 1]
)

print(kosis.shape)
kosis.head()

(25, 73)

  행정구역(시군구)별 2024.01                                                        \
  행정구역(시군구)별 총전입 (명) 총전출 (명) 시도내이동-시군구간 전입 (명) 시도내이동-시군구간 전출 (명) 시도간전입 (명)
0        종로구    1725    1704               846               914       713
1         중구    1587    1551               820               833       601
2        용산구    2638    3600              1079              1913      1019
3        성동구    3147    3410              1519              1751      1178
4        광진구    3903    4104              1471              1682      1623

            2024.02                            ...           2024.11  \
  시도간전출 (명) 총전입 (명) 총전출 (명) 시도내이동-시군구간 전입 (명)  ... 시도내이동-시군구간 전입 (명)
0       624    2356    2208              1082  ...               631
1       552    2050    1908               996  ...               626
2      1147    3067    3988              1307  ...               891
3      1209    4202    4365              1886  ...              1228
4      1613    4948    5038              1878  ...              1319

                                        2024.12                            \
  시도내이동-시군구간 전출 (명) 시도간전입 (명) 시도간전출 (명) 총전입 (명) 총전출 (명) 시도내이동-시군구간 전입 (명)
0               769       428       414    1363    1581               695
1               752       363       425    1315    1658               659
2              1160       646       737    2222    2452              1029
3              1635       692       932    2523    3151              1230
4              1477       977      1095    3424    4038              1425


  시도내이동-시군구간 전출 (명) 시도간전입 (명) 시도간전출 (명)
0               842       490       561
1               908       439       533
2              1252       813       820
3              1737       830       951
4              1894      1215      1360

[5 rows x 73 columns]

In [24]:
rows = []

for _, row in kosis.iterrows():
    gu = row.iloc[0]

    for month in range(1, 13):
        ym = f"2024.{month:02d}"

        rows.append({
            "guName": gu,
            "yearMonth": ym.replace(".", "-"),
            "moveIn": row[(ym, "총전입 (명)")],
            "moveOut": row[(ym, "총전출 (명)")]
        })

migration = pd.DataFrame(rows)

print(migration.shape)
migration.head()

(300, 4)

  guName yearMonth  moveIn  moveOut
0    종로구   2024-01    1725     1704
1    종로구   2024-02    2356     2208
2    종로구   2024-03    1861     1798
3    종로구   2024-04    1595     1625
4    종로구   2024-05    1409     1469

In [25]:
migration["moveIn"] = pd.to_numeric(migration["moveIn"], errors="coerce")
migration["moveOut"] = pd.to_numeric(migration["moveOut"], errors="coerce")

migration["netMove"] = migration["moveIn"] - migration["moveOut"]

print(migration.dtypes)
migration.head()

guName         str
yearMonth      str
moveIn       int64
moveOut      int64
netMove      int64
dtype: object

  guName yearMonth  moveIn  moveOut  netMove
0    종로구   2024-01    1725     1704       21
1    종로구   2024-02    2356     2208      148
2    종로구   2024-03    1861     1798       63
3    종로구   2024-04    1595     1625      -30
4    종로구   2024-05    1409     1469      -60

In [26]:
migration.to_csv(
    "../data/processed/kosis_migration_2024_clean.csv",
    index=False,
    encoding="utf-8-sig"
)

print("저장 완료:", migration.shape)

저장 완료: (300, 5)

In [27]:
migration.to_sql(
    name="migration",
    con=engine,
    if_exists="replace",
    index=False
)

print("MySQL 저장 완료:", len(migration))

MySQL 저장 완료: 300

In [28]:
query = """
SELECT
    guName,
    CONCAT(dealYear, '-', LPAD(dealMonth, 2, '0')) AS yearMonth,
    COUNT(*) AS contractCount
FROM rental_transactions
GROUP BY guName, dealYear, dealMonth
ORDER BY guName, dealYear, dealMonth;
"""

rent_monthly = pd.read_sql(query, engine)

print(rent_monthly.shape)
rent_monthly.head()

(300, 3)

  guName yearMonth  contractCount
0    강남구   2024-01           2464
1    강남구   2024-02           1985
2    강남구   2024-03           1976
3    강남구   2024-04           1651
4    강남구   2024-05           2539

In [29]:
query = """
SELECT
    r.guName,
    r.yearMonth,
    r.contractCount,
    m.moveIn,
    m.moveOut,
    m.netMove
FROM (
    SELECT
        guName,
        CONCAT(dealYear, '-', LPAD(dealMonth, 2, '0')) AS yearMonth,
        COUNT(*) AS contractCount
    FROM rental_transactions
    GROUP BY guName, dealYear, dealMonth
) r
JOIN migration m
    ON r.guName = m.guName
    AND r.yearMonth = m.yearMonth
ORDER BY r.guName, r.yearMonth;
"""

market = pd.read_sql(query, engine)

print(market.shape)
market.head()

(300, 6)

  guName yearMonth  contractCount  moveIn  moveOut  netMove
0    강남구   2024-01           2464   13140     8937     4203
1    강남구   2024-02           1985   14454    10088     4366
2    강남구   2024-03           1976    7752     7059      693
3    강남구   2024-04           1651    6948     6624      324
4    강남구   2024-05           2539    6824     5592     1232

In [30]:
market.to_sql(
    name="monthly_rent_market",
    con=engine,
    if_exists="replace",
    index=False
)

print("저장 완료:", len(market))

저장 완료: 300

In [31]:
ecos = pd.read_csv(
    "../data/raw/ecos_base_rate_2024.csv",
    encoding="utf-8"
)

print(ecos.shape)
print(ecos.columns.tolist())
ecos.head()

(12, 16)
['통계표', '계정항목', '단위', '변환', '2024/01', '2024/02', '2024/03', '2024/04', '2024/05', '2024/06', '2024/07', '2024/08', '2024/09', '2024/10', '2024/11', '2024/12']

,통계표,계정항목,단위,변환,2024/01,2024/02,2024/03,2024/04,2024/05,2024/06,2024/07,2024/08,2024/09,2024/10,2024/11,2024/12
0,1.3.1. 한국은행 기준금리 및 여수신금리,한국은행 기준금리,연%,원자료,3.500,3.500,3.500,3.500,3.500,3.500,3.500,3.500,3.500,3.250,3.000,3.000
1,1.3.1. 한국은행 기준금리 및 여수신금리,정부대출금금리,연%,원자료,3.623,3.623,3.623,3.563,3.563,3.563,3.543,3.543,3.543,3.302,3.302,3.302
2,1.3.1. 한국은행 기준금리 및 여수신금리,총액한도대출금리,연%,원자료,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.3.1. 한국은행 기준금리 및 여수신금리,결제자금지원한도 대출금리,연%,원자료,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.3.1. 한국은행 기준금리 및 여수신금리,무역금융지원 프로그램대출금리,연%,원자료,2.000,2.000,2.000,2.000,2.000,2.000,2.000,2.000,2.000,1.750,1.500,1.500

In [32]:
print(ecos["계정항목"].tolist())

['한국은행 기준금리', '정부대출금금리', '총액한도대출금리', '결제자금지원한도 대출금리', '무역금융지원 프로그램대출금리', '신용대출지원 프로그램대출금리', '영세자영업자지원 프로그램대출금리', '신성장·일자리지원 프로그램대출금리', '설비투자지원 프로그램대출금리', '지방중소기업지원 프로그램대출금리', '자금조정 대출금리', '자금조정 예금금리']

In [33]:
rate_row = ecos[ecos["계정항목"] == "한국은행 기준금리"].iloc[0]

rates = []

for month in range(1, 13):
    col = f"2024/{month:02d}"

    rates.append({
        "yearMonth": f"2024-{month:02d}",
        "baseRate": rate_row[col]
    })

interest_rate = pd.DataFrame(rates)

interest_rate["baseRate"] = pd.to_numeric(
    interest_rate["baseRate"],
    errors="coerce"
)

print(interest_rate.shape)
interest_rate

(12, 2)

   yearMonth  baseRate
0    2024-01      3.50
1    2024-02      3.50
2    2024-03      3.50
3    2024-04      3.50
4    2024-05      3.50
5    2024-06      3.50
6    2024-07      3.50
7    2024-08      3.50
8    2024-09      3.50
9    2024-10      3.25
10   2024-11      3.00
11   2024-12      3.00

In [34]:
interest_rate.to_sql(
    name="interest_rate",
    con=engine,
    if_exists="replace",
    index=False
)

print("MySQL 저장 완료:", len(interest_rate))

MySQL 저장 완료: 12

In [35]:
query = """
SELECT
    m.guName,
    m.yearMonth,
    m.contractCount,
    m.moveIn,
    m.moveOut,
    m.netMove,
    i.baseRate
FROM monthly_rent_market m
JOIN interest_rate i
    ON m.yearMonth = i.yearMonth
ORDER BY m.guName, m.yearMonth;
"""

market_final = pd.read_sql(query, engine)

print(market_final.shape)
market_final.head()

(300, 7)

  guName yearMonth  contractCount  moveIn  moveOut  netMove  baseRate
0    강남구   2024-01           2464   13140     8937     4203       3.5
1    강남구   2024-02           1985   14454    10088     4366       3.5
2    강남구   2024-03           1976    7752     7059      693       3.5
3    강남구   2024-04           1651    6948     6624      324       3.5
4    강남구   2024-05           2539    6824     5592     1232       3.5

In [36]:
market_final.to_sql(
    name="monthly_rent_market_final",
    con=engine,
    if_exists="replace",
    index=False
)

print("최종 테이블 저장 완료:", len(market_final))

최종 테이블 저장 완료: 300

In [37]:
seoul_pop = pd.read_csv(
    "../data/raw/LOCAL_PEOPLE_GU_2024.csv",
    encoding="utf-8"
)

print(seoul_pop.shape)
print(seoul_pop.columns.tolist())
seoul_pop.head()

(219600, 33)
['stdr_de_id', 'tmzon_pd_se', 'adstrd_code_se', 'tot_lvpop_co', 'male_f0t9_lvpop_co', 'male_f10t14_lvpop_co', 'male_f15t19_lvpop_co', 'male_f20t24_lvpop_co', 'male_f25t29_lvpop_co', 'male_f30t34_lvpop_co', 'male_f35t39_lvpop_co', 'male_f40t44_lvpop_co', 'male_f45t49_lvpop_co', 'male_f50t54_lvpop_co', 'male_f55t59_lvpop_co', 'male_f60t64_lvpop_co', 'male_f65t69_lvpop_co', 'male_f70t74_lvpop_co', 'female_f0t9_lvpop_co', 'female_f10t14_lvpop_co', 'female_f15t19_lvpop_co', 'female_f20t24_lvpop_co', 'female_f25t29_lvpop_co', 'female_f30t34_lvpop_co', 'female_f35t39_lvpop_co', 'female_f40t44_lvpop_co', 'female_f45t49_lvpop_co', 'female_f50t54_lvpop_co', 'female_f55t59_lvpop_co', 'female_f60t64_lvpop_co', 'female_f65t69_lvpop_co', 'female_f70t74_lvpop_co', 'ldadng_dt']

,stdr_de_id,tmzon_pd_se,adstrd_code_se,tot_lvpop_co,male_f0t9_lvpop_co,male_f10t14_lvpop_co,male_f15t19_lvpop_co,male_f20t24_lvpop_co,male_f25t29_lvpop_co,male_f30t34_lvpop_co,...,female_f30t34_lvpop_co,female_f35t39_lvpop_co,female_f40t44_lvpop_co,female_f45t49_lvpop_co,female_f50t54_lvpop_co,female_f55t59_lvpop_co,female_f60t64_lvpop_co,female_f65t69_lvpop_co,female_f70t74_lvpop_co,ldadng_dt
0,20240101,0,11110,231940.9131,6080.9363,3260.2185,7037.7728,11720.3719,11453.5946,9398.7762,...,8270.8979,8262.8127,7381.2943,8933.9256,8204.0952,8077.3270,6773.4574,5040.6403,13601.2481,20240106080757
1,20240101,0,11140,182354.5506,5902.9352,2159.7405,3988.1295,8122.6534,9192.2022,8468.1934,...,8025.3593,8376.7658,6437.4373,6552.0269,5470.2929,5710.5258,4853.0913,3468.4969,9611.2688,20240106080757
2,20240101,0,11170,255885.5460,7345.2048,3639.3568,5057.8888,9234.4375,12070.7663,12527.3087,...,11832.5148,13239.7348,10843.0989,10513.5132,9354.6379,8665.0049,7487.8939,5751.9700,15265.4809,20240106080757
3,20240101,0,11200,302502.4326,10581.9842,4442.1591,6422.9086,9393.7985,12003.4389,11298.4993,...,12224.1674,15389.4293,12996.5818,12855.6322,11768.9656,11444.6560,9825.7494,7485.4514,18810.1096,20240106080757
4,20240101,0,11215,360329.9580,11123.9665,5904.0852,11819.2905,15020.4273,16807.9300,14211.2764,...,13959.7815,15187.1613,13256.5885,14758.9090,12738.2737,13649.9078,11219.6742,8644.5426,20246.3334,20240106080757

In [38]:
seoul_pop = pd.read_csv(
    "../data/raw/LOCAL_PEOPLE_GU_2024.csv",
    encoding="utf-8"
)

print(seoul_pop.shape)
print(seoul_pop.columns.tolist())
seoul_pop.head()

(219600, 33)
['stdr_de_id', 'tmzon_pd_se', 'adstrd_code_se', 'tot_lvpop_co', 'male_f0t9_lvpop_co', 'male_f10t14_lvpop_co', 'male_f15t19_lvpop_co', 'male_f20t24_lvpop_co', 'male_f25t29_lvpop_co', 'male_f30t34_lvpop_co', 'male_f35t39_lvpop_co', 'male_f40t44_lvpop_co', 'male_f45t49_lvpop_co', 'male_f50t54_lvpop_co', 'male_f55t59_lvpop_co', 'male_f60t64_lvpop_co', 'male_f65t69_lvpop_co', 'male_f70t74_lvpop_co', 'female_f0t9_lvpop_co', 'female_f10t14_lvpop_co', 'female_f15t19_lvpop_co', 'female_f20t24_lvpop_co', 'female_f25t29_lvpop_co', 'female_f30t34_lvpop_co', 'female_f35t39_lvpop_co', 'female_f40t44_lvpop_co', 'female_f45t49_lvpop_co', 'female_f50t54_lvpop_co', 'female_f55t59_lvpop_co', 'female_f60t64_lvpop_co', 'female_f65t69_lvpop_co', 'female_f70t74_lvpop_co', 'ldadng_dt']

,stdr_de_id,tmzon_pd_se,adstrd_code_se,tot_lvpop_co,male_f0t9_lvpop_co,male_f10t14_lvpop_co,male_f15t19_lvpop_co,male_f20t24_lvpop_co,male_f25t29_lvpop_co,male_f30t34_lvpop_co,...,female_f30t34_lvpop_co,female_f35t39_lvpop_co,female_f40t44_lvpop_co,female_f45t49_lvpop_co,female_f50t54_lvpop_co,female_f55t59_lvpop_co,female_f60t64_lvpop_co,female_f65t69_lvpop_co,female_f70t74_lvpop_co,ldadng_dt
0,20240101,0,11110,231940.9131,6080.9363,3260.2185,7037.7728,11720.3719,11453.5946,9398.7762,...,8270.8979,8262.8127,7381.2943,8933.9256,8204.0952,8077.3270,6773.4574,5040.6403,13601.2481,20240106080757
1,20240101,0,11140,182354.5506,5902.9352,2159.7405,3988.1295,8122.6534,9192.2022,8468.1934,...,8025.3593,8376.7658,6437.4373,6552.0269,5470.2929,5710.5258,4853.0913,3468.4969,9611.2688,20240106080757
2,20240101,0,11170,255885.5460,7345.2048,3639.3568,5057.8888,9234.4375,12070.7663,12527.3087,...,11832.5148,13239.7348,10843.0989,10513.5132,9354.6379,8665.0049,7487.8939,5751.9700,15265.4809,20240106080757
3,20240101,0,11200,302502.4326,10581.9842,4442.1591,6422.9086,9393.7985,12003.4389,11298.4993,...,12224.1674,15389.4293,12996.5818,12855.6322,11768.9656,11444.6560,9825.7494,7485.4514,18810.1096,20240106080757
4,20240101,0,11215,360329.9580,11123.9665,5904.0852,11819.2905,15020.4273,16807.9300,14211.2764,...,13959.7815,15187.1613,13256.5885,14758.9090,12738.2737,13649.9078,11219.6742,8644.5426,20246.3334,20240106080757

In [39]:
print(seoul_pop["stdr_de_id"].head())
print(seoul_pop["stdr_de_id"].dtype)

0    20240101
1    20240101
2    20240101
3    20240101
4    20240101
Name: stdr_de_id, dtype: int64
int64

In [40]:
seoul_pop["yearMonth"] = (
    seoul_pop["stdr_de_id"]
    .astype(str)
    .str[:6]
    .str[:4] + "-" +
    seoul_pop["stdr_de_id"]
    .astype(str)
    .str[4:6]
)

print(seoul_pop["yearMonth"].unique())

<StringArray>
['2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07',
 '2024-08', '2024-09', '2024-10', '2024-11', '2024-12']
Length: 12, dtype: str

In [41]:
print(seoul_pop["adstrd_code_se"].nunique())
print(sorted(seoul_pop["adstrd_code_se"].unique()))

25
[np.int64(11110), np.int64(11140), np.int64(11170), np.int64(11200), np.int64(11215), np.int64(11230), np.int64(11260), np.int64(11290), np.int64(11305), np.int64(11320), np.int64(11350), np.int64(11380), np.int64(11410), np.int64(11440), np.int64(11470), np.int64(11500), np.int64(11530), np.int64(11545), np.int64(11560), np.int64(11590), np.int64(11620), np.int64(11650), np.int64(11680), np.int64(11710), np.int64(11740)]

In [42]:
code_to_gu = {int(code): name for name, code in seoul_gu.items()}

seoul_pop["guName"] = seoul_pop["adstrd_code_se"].map(code_to_gu)

print(seoul_pop["guName"].nunique())
print(seoul_pop["guName"].isnull().sum())

25
0

In [43]:
living_pop = (
    seoul_pop
    .groupby(["guName", "yearMonth"])["tot_lvpop_co"]
    .mean()
    .reset_index()
    .rename(columns={"tot_lvpop_co": "avgLivingPop"})
)

print(living_pop.shape)
living_pop.head()

(300, 3)

  guName yearMonth   avgLivingPop
0    강남구   2024-01  814365.906419
1    강남구   2024-02  812009.586478
2    강남구   2024-03  826818.317374
3    강남구   2024-04  824744.923619
4    강남구   2024-05  816933.047707

In [44]:
living_pop.to_sql(
    name="living_population",
    con=engine,
    if_exists="replace",
    index=False
)

print("MySQL 저장 완료:", len(living_pop))

MySQL 저장 완료: 300

In [45]:
query = """
SELECT
    m.guName,
    m.yearMonth,
    m.contractCount,
    m.moveIn,
    m.moveOut,
    m.netMove,
    m.baseRate,
    l.avgLivingPop
FROM monthly_rent_market_final m
JOIN living_population l
    ON m.guName = l.guName
    AND m.yearMonth = l.yearMonth
ORDER BY m.guName, m.yearMonth;
"""

ml_data = pd.read_sql(query, engine)

print(ml_data.shape)
ml_data.head()

(300, 8)

,guName,yearMonth,contractCount,moveIn,moveOut,netMove,baseRate,avgLivingPop
0,강남구,2024-01,2464,13140,8937,4203,3.5,814365.906419
1,강남구,2024-02,1985,14454,10088,4366,3.5,812009.586478
2,강남구,2024-03,1976,7752,7059,693,3.5,826818.317374
3,강남구,2024-04,1651,6948,6624,324,3.5,824744.923619
4,강남구,2024-05,2539,6824,5592,1232,3.5,816933.047707

In [46]:
ml_data.to_sql(
    name="ml_rent_market",
    con=engine,
    if_exists="replace",
    index=False
)

print("ML 테이블 저장 완료:", len(ml_data))

ML 테이블 저장 완료: 300

여기까지 2024년 이후 2023년, 2025년 추가

In [47]:
years = [2023, 2024, 2025]

months = [
    f"{year}{month:02d}"
    for year in years
    for month in range(1, 13)
]

print(months)
print("총 개월 수:", len(months))

['202301', '202302', '202303', '202304', '202305', '202306', '202307', '202308', '202309', '202310', '202311', '202312', '202401', '202402', '202403', '202404', '202405', '202406', '202407', '202408', '202409', '202410', '202411', '202412', '202501', '202502', '202503', '202504', '202505', '202506', '202507', '202508', '202509', '202510', '202511', '202512']
총 개월 수: 36

In [48]:
all_rows_extra = []

for gu_name, gu_code in seoul_gu.items():
    for year in [2023, 2025]:
        for month in range(1, 13):
            ymd = f"{year}{month:02d}"

            url = (
                "https://apis.data.go.kr/1613000/RTMSDataSvcAptRent/getRTMSDataSvcAptRent"
                f"?serviceKey={API_KEY}"
                f"&LAWD_CD={gu_code}"
                f"&DEAL_YMD={ymd}"
                "&numOfRows=5000"
                "&pageNo=1"
            )

            response = requests.get(url)
            root = ET.fromstring(response.text)
            items = root.findall(".//item")

            for item in items:
                row = {child.tag: child.text for child in item}
                row["guName"] = gu_name
                all_rows_extra.append(row)

            print(gu_name, ymd, len(items))
            time.sleep(0.2)

df_seoul_extra = pd.DataFrame(all_rows_extra)

print("추가 데이터:", df_seoul_extra.shape)

종로구 202301 180
종로구 202302 205
종로구 202303 193
종로구 202304 189
종로구 202305 211
종로구 202306 165
종로구 202307 182
종로구 202308 218
종로구 202309 219
종로구 202310 196
종로구 202311 236
종로구 202312 223
종로구 202501 184
종로구 202502 250
종로구 202503 190
종로구 202504 176
종로구 202505 181
종로구 202506 210
종로구 202507 203
종로구 202508 194
종로구 202509 217
종로구 202510 197
종로구 202511 221
종로구 202512 290
중구 202301 304
중구 202302 434
중구 202303 386
중구 202304 410
중구 202305 576
중구 202306 494
중구 202307 368
중구 202308 341
중구 202309 363
중구 202310 332
중구 202311 312
중구 202312 319
중구 202501 311
중구 202502 375
중구 202503 409
중구 202504 373
중구 202505 430
중구 202506 435
중구 202507 366
중구 202508 315
중구 202509 368
중구 202510 286
중구 202511 311
중구 202512 375
용산구 202301 675
용산구 202302 559
용산구 202303 639
용산구 202304 598
용산구 202305 566
용산구 202306 642
용산구 202307 574
용산구 202308 507
용산구 202309 505
용산구 202310 466
용산구 202311 465
용산구 202312 545
용산구 202501 442
용산구 202502 571
용산구 202503 596
용산구 202504 596
용산구 202505 596
용산구 202506 609
용산구 202507 580
용산구 202508 453
용산구 202509 649
용산구 202510 464
용산구 202511 464
용산구 202512 593
성동구 202301 972
성동구 202302 1125
성동구 202303 1127
성동구 202304 977
성동구 202305 899
성동구 202306 941
성동구 202307 938
성동구 202308 811
성동구 202309 766
성동구 202310 872
성동구 202311 844
성동구 202312 865
성동구 202501 853
성동구 202502 1030
성동구 202503 1106
성동구 202504 980
성동구 202505 1007
성동구 202506 1081
성동구 202507 1162
성동구 202508 1007
성동구 202509 982
성동구 202510 816
성동구 202511 967
성동구 202512 946
광진구 202301 439
광진구 202302 499
광진구 202303 536
광진구 202304 428
광진구 202305 415
광진구 202306 496
광진구 202307 495
광진구 202308 423
광진구 202309 352
광진구 202310 463
광진구 202311 426
광진구 202312 430
광진구 202501 459
광진구 202502 500
광진구 202503 555
광진구 202504 550
광진구 202505 453
광진구 202506 491
광진구 202507 459
광진구 202508 368
광진구 202509 549
광진구 202510 419
광진구 202511 562
광진구 202512 501
동대문구 202301 672
동대문구 202302 854
동대문구 202303 897
동대문구 202304 781
동대문구 202305 700
동대문구 202306 842
동대문구 202307 839
동대문구 202308 754
동대문구 202309 659
동대문구 202310 619
동대문구 202311 622
동대문구 202312 712
동대문구 202501 1148
동대문구 202502 1248
동대문구 202503 1098
동대문구 202504 878
동대문구 202505 1106
동대문구 202506 1083
동대문구 202507 998
동대문구 202508 839
동대문구 202509 767
동대문구 202510 776
동대문구 202511 849
동대문구 202512 1187
중랑구 202301 493
중랑구 202302 647
중랑구 202303 539
중랑구 202304 497
중랑구 202305 598
중랑구 202306 484
중랑구 202307 502
중랑구 202308 521
중랑구 202309 505
중랑구 202310 624
중랑구 202311 814
중랑구 202312 670
중랑구 202501 408
중랑구 202502 539
중랑구 202503 515
중랑구 202504 448
중랑구 202505 577
중랑구 202506 516
중랑구 202507 515
중랑구 202508 441
중랑구 202509 891
중랑구 202510 661
중랑구 202511 672
중랑구 202512 809
성북구 202301 942
성북구 202302 1124
성북구 202303 1147
성북구 202304 924
성북구 202305 801
성북구 202306 744
성북구 202307 803
성북구 202308 727
성북구 202309 766
성북구 202310 752
성북구 202311 745
성북구 202312 908
성북구 202501 776
성북구 202502 947
성북구 202503 1004
성북구 202504 902
성북구 202505 1043
성북구 202506 1023
성북구 202507 826
성북구 202508 651
성북구 202509 769
성북구 202510 670
성북구 202511 764
성북구 202512 914
강북구 202301 224
강북구 202302 308
강북구 202303 368
강북구 202304 307
강북구 202305 317
강북구 202306 312
강북구 202307 316
강북구 202308 261
강북구 202309 287
강북구 202310 247
강북구 202311 252
강북구 202312 289
강북구 202501 323
강북구 202502 295
강북구 202503 258
강북구 202504 300
강북구 202505 250
강북구 202506 227
강북구 202507 276
강북구 202508 224
강북구 202509 300
강북구 202510 198
강북구 202511 232
강북구 202512 287
도봉구 202301 430
도봉구 202302 607
도봉구 202303 634
도봉구 202304 506
도봉구 202305 562
도봉구 202306 540
도봉구 202307 573
도봉구 202308 581
도봉구 202309 473
도봉구 202310 526
도봉구 202311 554
도봉구 202312 526
도봉구 202501 395
도봉구 202502 506
도봉구 202503 558
도봉구 202504 522
도봉구 202505 497
도봉구 202506 534
도봉구 202507 582
도봉구 202508 536
도봉구 202509 545
도봉구 202510 436
도봉구 202511 455
도봉구 202512 449
노원구 202301 1501
노원구 202302 2043
노원구 202303 1871
노원구 202304 1499
노원구 202305 1529
노원구 202306 1696
노원구 202307 1784
노원구 202308 1622
노원구 202309 1698
노원구 202310 1772
노원구 202311 1740
노원구 202312 1758
노원구 202501 1265
노원구 202502 1689
노원구 202503 1723
노원구 202504 1568
노원구 202505 1592
노원구 202506 1594
노원구 202507 1530
노원구 202508 1468
노원구 202509 1730
노원구 202510 1545
노원구 202511 1659
노원구 202512 1549
은평구 202301 747
은평구 202302 895
은평구 202303 871
은평구 202304 819
은평구 202305 852
은평구 202306 882
은평구 202307 987
은평구 202308 1011
은평구 202309 863
은평구 202310 941
은평구 202311 608
은평구 202312 924
은평구 202501 713
은평구 202502 838
은평구 202503 832
은평구 202504 742
은평구 202505 668
은평구 202506 709
은평구 202507 782
은평구 202508 677
은평구 202509 735
은평구 202510 796
은평구 202511 667
은평구 202512 1065
서대문구 202301 881
서대문구 202302 914
서대문구 202303 771
서대문구 202304 628
서대문구 202305 535
서대문구 202306 623
서대문구 202307 649
서대문구 202308 524
서대문구 202309 560
서대문구 202310 595
서대문구 202311 663
서대문구 202312 759
서대문구 202501 656
서대문구 202502 751
서대문구 202503 682
서대문구 202504 628
서대문구 202505 612
서대문구 202506 639
서대문구 202507 607
서대문구 202508 545
서대문구 202509 561
서대문구 202510 512
서대문구 202511 683
서대문구 202512 829
마포구 202301 1644
마포구 202302 1354
마포구 202303 1279
마포구 202304 1105
마포구 202305 1057
마포구 202306 1390
마포구 202307 1058
마포구 202308 960
마포구 202309 903
마포구 202310 1049
마포구 202311 947
마포구 202312 1116
마포구 202501 1322
마포구 202502 1194
마포구 202503 1163
마포구 202504 1137
마포구 202505 1063
마포구 202506 1007
마포구 202507 979
마포구 202508 939
마포구 202509 1009
마포구 202510 1022
마포구 202511 1067
마포구 202512 1184
양천구 202301 1011
양천구 202302 1098
양천구 202303 1061
양천구 202304 1210
양천구 202305 967
양천구 202306 1041
양천구 202307 948
양천구 202308 1195
양천구 202309 992
양천구 202310 1208
양천구 202311 1065
양천구 202312 1041
양천구 202501 872
양천구 202502 1021
양천구 202503 1018
양천구 202504 991
양천구 202505 984
양천구 202506 1058
양천구 202507 960
양천구 202508 1129
양천구 202509 919
양천구 202510 996
양천구 202511 1081
양천구 202512 1097
강서구 202301 1107
강서구 202302 1575
강서구 202303 1421
강서구 202304 1377
강서구 202305 1270
강서구 202306 1519
강서구 202307 1224
강서구 202308 1168
강서구 202309 1157
강서구 202310 1328
강서구 202311 1287
강서구 202312 1294
강서구 202501 1069
강서구 202502 1430
강서구 202503 1281
강서구 202504 1278
강서구 202505 1398
강서구 202506 1495
강서구 202507 1223
강서구 202508 1209
강서구 202509 1122
강서구 202510 1206
강서구 202511 1159
강서구 202512 1311
구로구 202301 923
구로구 202302 1268
구로구 202303 1005
구로구 202304 1375
구로구 202305 812
구로구 202306 803
구로구 202307 729
구로구 202308 960
구로구 202309 878
구로구 202310 967
구로구 202311 717
구로구 202312 982
구로구 202501 851
구로구 202502 1049
구로구 202503 920
구로구 202504 1058
구로구 202505 858
구로구 202506 730
구로구 202507 699
구로구 202508 845
구로구 202509 853
구로구 202510 942
구로구 202511 752
구로구 202512 1091
금천구 202301 335
금천구 202302 290
금천구 202303 646
금천구 202304 630
금천구 202305 536
금천구 202306 401
금천구 202307 264
금천구 202308 344
금천구 202309 268
금천구 202310 302
금천구 202311 302
금천구 202312 283
금천구 202501 295
금천구 202502 318
금천구 202503 479
금천구 202504 498
금천구 202505 490
금천구 202506 337
금천구 202507 287
금천구 202508 255
금천구 202509 302
금천구 202510 223
금천구 202511 246
금천구 202512 288
영등포구 202301 866
영등포구 202302 1111
영등포구 202303 1181
영등포구 202304 940
영등포구 202305 956
영등포구 202306 899
영등포구 202307 872
영등포구 202308 992
영등포구 202309 856
영등포구 202310 871
영등포구 202311 898
영등포구 202312 985
영등포구 202501 836
영등포구 202502 1074
영등포구 202503 1146
영등포구 202504 954
영등포구 202505 881
영등포구 202506 1000
영등포구 202507 1095
영등포구 202508 842
영등포구 202509 925
영등포구 202510 820
영등포구 202511 949
영등포구 202512 984
동작구 202301 783
동작구 202302 1021
동작구 202303 988
동작구 202304 756
동작구 202305 877
동작구 202306 806
동작구 202307 742
동작구 202308 725
동작구 202309 660
동작구 202310 787
동작구 202311 715
동작구 202312 875
동작구 202501 758
동작구 202502 1019
동작구 202503 1062
동작구 202504 854
동작구 202505 846
동작구 202506 931
동작구 202507 766
동작구 202508 738
동작구 202509 729
동작구 202510 703
동작구 202511 704
동작구 202512 882
관악구 202301 646
관악구 202302 683
관악구 202303 648
관악구 202304 529
관악구 202305 575
관악구 202306 610
관악구 202307 708
관악구 202308 528
관악구 202309 499
관악구 202310 543
관악구 202311 505
관악구 202312 609
관악구 202501 520
관악구 202502 687
관악구 202503 632
관악구 202504 550
관악구 202505 562
관악구 202506 561
관악구 202507 534
관악구 202508 521
관악구 202509 505
관악구 202510 467
관악구 202511 510
관악구 202512 580
서초구 202301 1256
서초구 202302 1734
서초구 202303 1606
서초구 202304 1390
서초구 202305 1404
서초구 202306 1906
서초구 202307 1650
서초구 202308 1737
서초구 202309 1449
서초구 202310 1695
서초구 202311 1353
서초구 202312 1558
서초구 202501 1159
서초구 202502 1508
서초구 202503 1696
서초구 202504 1443
서초구 202505 1544
서초구 202506 1710
서초구 202507 1715
서초구 202508 1850
서초구 202509 1444
서초구 202510 1456
서초구 202511 1506
서초구 202512 1520
강남구 202301 2171
강남구 202302 2825
강남구 202303 3016
강남구 202304 2354
강남구 202305 2291
강남구 202306 2381
강남구 202307 2101
강남구 202308 2127
강남구 202309 2066
강남구 202310 2327
강남구 202311 2474
강남구 202312 3448
강남구 202501 1672
강남구 202502 2344
강남구 202503 2120
강남구 202504 1988
강남구 202505 2236
강남구 202506 2028
강남구 202507 1969
강남구 202508 1978
강남구 202509 2000
강남구 202510 2071
강남구 202511 2732
강남구 202512 2798
송파구 202301 2276
송파구 202302 2727
송파구 202303 2317
송파구 202304 2069
송파구 202305 2606
송파구 202306 1535
송파구 202307 1647
송파구 202308 1419
송파구 202309 1566
송파구 202310 1829
송파구 202311 1744
송파구 202312 2757
송파구 202501 2181
송파구 202502 2326
송파구 202503 2118
송파구 202504 1944
송파구 202505 2286
송파구 202506 1523
송파구 202507 1568
송파구 202508 1241
송파구 202509 1419
송파구 202510 1572
송파구 202511 1859
송파구 202512 2770
강동구 202301 1124
강동구 202302 2985
강동구 202303 2187
강동구 202304 1522
강동구 202305 1321
강동구 202306 1477
강동구 202307 1246
강동구 202308 1403
강동구 202309 1614
강동구 202310 1495
강동구 202311 1338
강동구 202312 1587
강동구 202501 1414
강동구 202502 3021
강동구 202503 2197
강동구 202504 1427
강동구 202505 1421
강동구 202506 1495
강동구 202507 1269
강동구 202508 1189
강동구 202509 1501
강동구 202510 1401
강동구 202511 1400
강동구 202512 1425
추가 데이터: (559587, 26)

In [49]:
df_seoul_3years = pd.concat(
    [df_seoul_2024, df_seoul_extra],
    ignore_index=True
)

print("3개년 전체:", df_seoul_3years.shape)

3개년 전체: (812501, 26)

In [50]:
print("전체 행:", len(df_seoul_3years))
print("완전 중복 행:", df_seoul_3years.duplicated().sum())

전체 행: 812501
완전 중복 행: 36530

In [51]:
df_seoul_3years = df_seoul_3years.drop_duplicates().reset_index(drop=True)

print("중복 제거 후:", df_seoul_3years.shape)
print("남은 중복:", df_seoul_3years.duplicated().sum())

중복 제거 후: (775971, 26)
남은 중복: 0

In [52]:
df_seoul_3years["dealYear"] = pd.to_numeric(
    df_seoul_3years["dealYear"], errors="coerce"
)

print(df_seoul_3years["dealYear"].value_counts().sort_index())

dealYear
2023    273194
2024    240326
2025    262451
Name: count, dtype: int64

In [53]:
dup_2024 = df_seoul_2024[df_seoul_2024.duplicated(keep=False)]

print("2024 중복 관련 행:", len(dup_2024))
print(dup_2024.head())

2024 중복 관련 행: 24230
       aptNm      aptSeq buildYear contractTerm contractType dealDay  \
23   인왕산아이파크  11110-2212      2008  24.02~26.02           신규      10
32  힐스테이트창경궁  11110-2584      2022  24.03~26.03           신규      14
38        현대    11110-90      2000  24.02~26.02           신규      12
42       아남1    11110-25      1995  24.02~26.02           신규       2
72  힐스테이트창경궁  11110-2584      2022  24.02~26.02           신규      16

   dealMonth dealYear deposit excluUseAr  ... roadnmbcd roadnmbonbun  \
23         1     2024  80,000     84.858  ...         0        00009
32         1     2024  90,000      84.95  ...         0        00236
38         1     2024  48,500         60  ...         0        00246
42         1     2024  50,000       84.9  ...         0        00265
72         1     2024  95,000      84.97  ...         0        00236

   roadnmbubun roadnmcd roadnmseq roadnmsggcd  sggCd umdNm useRRRight guName
23       00000  4100482         1       11110  11110   무악동               종로구
32       00000  3100010         0       11110  11110   충신동               종로구
38       00009  3000008         6       11110  11110   무악동               종로구
42       00000  3005008         7       11110  11110  명륜2가               종로구
72       00000  3100010         0       11110  11110   충신동               종로구

[5 rows x 26 columns]

In [54]:
df_seoul_3years = pd.concat(
    [df_seoul_2024, df_seoul_extra],
    ignore_index=True
)

print(df_seoul_3years.shape)
print(df_seoul_3years["dealYear"].value_counts().sort_index())

(812501, 26)
dealYear
2023    284380
2024    252914
2025    275207
Name: count, dtype: int64

In [55]:
df_clean = df_seoul_3years.copy()

df_clean["deposit"] = (
    df_clean["deposit"]
    .str.replace(",", "", regex=False)
    .astype(int)
)

df_clean["monthlyRent"] = pd.to_numeric(
    df_clean["monthlyRent"], errors="coerce"
)

numeric_cols = [
    "excluUseAr", "floor", "buildYear",
    "dealYear", "dealMonth", "dealDay"
]

for col in numeric_cols:
    df_clean[col] = pd.to_numeric(df_clean[col], errors="coerce")

df_clean["dealDate"] = pd.to_datetime(
    df_clean["dealYear"].astype(str) + "-" +
    df_clean["dealMonth"].astype(str) + "-" +
    df_clean["dealDay"].astype(str)
)

df_clean["rentType"] = df_clean["monthlyRent"].apply(
    lambda x: "전세" if x == 0 else "월세"
)

print(df_clean.shape)
print(df_clean["rentType"].value_counts())

(812501, 28)
rentType
전세    464333
월세    348168
Name: count, dtype: int64

In [56]:
df_clean.to_csv(
    "../data/processed/seoul_rent_2023_2025_clean.csv",
    index=False,
    encoding="utf-8-sig"
)

print("저장 완료:", df_clean.shape)

저장 완료: (812501, 28)

In [57]:
df_clean.to_sql(
    "rental_transactions",
    engine,
    if_exists="replace",
    index=False,
    chunksize=5000
)

print("MySQL 저장 완료")

MySQL 저장 완료

In [58]:
monthly_check = pd.read_sql("""
SELECT
    guName,
    CONCAT(dealYear, '-', LPAD(dealMonth, 2, '0')) AS yearMonth,
    COUNT(*) AS contractCount
FROM rental_transactions
GROUP BY guName, dealYear, dealMonth
ORDER BY guName, dealYear, dealMonth
""", engine)

print(monthly_check.shape)
print(monthly_check["yearMonth"].min())
print(monthly_check["yearMonth"].max())

(900, 3)
2023-01
2025-12

In [62]:
kosis = pd.read_csv(
    "../data/raw/kosis_migration_2023_2025.csv",
    encoding="utf-8",
    header=[0, 1]
)

print(kosis.shape)
print(kosis.columns[:10])

(25, 289)
MultiIndex([('행정구역(시군구)별',        '행정구역(시군구)별'),
            (   '2023.01',           '총전입 (명)'),
            (   '2023.01',           '총전출 (명)'),
            (   '2023.01',           '순이동 (명)'),
            (   '2023.01',    '시도내이동-시군구내 (명)'),
            (   '2023.01', '시도내이동-시군구간 전입 (명)'),
            (   '2023.01', '시도내이동-시군구간 전출 (명)'),
            (   '2023.01',         '시도간전입 (명)'),
            (   '2023.01',         '시도간전출 (명)'),
            (   '2023.02',           '총전입 (명)')],
           )

In [63]:
rows = []

for _, row in kosis.iterrows():
    gu = row.iloc[0]

    for year in [2023, 2024, 2025]:
        for month in range(1, 13):
            ym = f"{year}.{month:02d}"

            rows.append({
                "guName": gu,
                "yearMonth": ym.replace(".", "-"),
                "moveIn": row[(ym, "총전입 (명)")],
                "moveOut": row[(ym, "총전출 (명)")],
                "netMove": row[(ym, "순이동 (명)")]
            })

migration = pd.DataFrame(rows)

for col in ["moveIn", "moveOut", "netMove"]:
    migration[col] = pd.to_numeric(migration[col], errors="coerce")

print(migration.shape)
print(migration.head())

(900, 5)
  guName yearMonth  moveIn  moveOut  netMove
0    종로구   2023-01    1420     1568     -148
1    종로구   2023-02    2298     2062      236
2    종로구   2023-03    1792     2124     -332
3    종로구   2023-04    1255     1408     -153
4    종로구   2023-05    1460     1698     -238

In [64]:
migration.to_sql(
    "migration",
    engine,
    if_exists="replace",
    index=False
)

print("MySQL migration:", len(migration))

MySQL migration: 900

In [65]:
ecos = pd.read_csv(
    "../data/raw/ecos_base_rate_2023_2025.csv",
    encoding="utf-8"
)

print(ecos.shape)
print(ecos.columns)

(1, 40)
Index(['통계표', '계정항목', '단위', '변환', '2023/01', '2023/02', '2023/03', '2023/04',
       '2023/05', '2023/06', '2023/07', '2023/08', '2023/09', '2023/10',
       '2023/11', '2023/12', '2024/01', '2024/02', '2024/03', '2024/04',
       '2024/05', '2024/06', '2024/07', '2024/08', '2024/09', '2024/10',
       '2024/11', '2024/12', '2025/01', '2025/02', '2025/03', '2025/04',
       '2025/05', '2025/06', '2025/07', '2025/08', '2025/09', '2025/10',
       '2025/11', '2025/12'],
      dtype='str')

In [66]:
rate_row = ecos.iloc[0]

rates = []

for year in [2023, 2024, 2025]:
    for month in range(1, 13):
        col = f"{year}/{month:02d}"

        rates.append({
            "yearMonth": f"{year}-{month:02d}",
            "baseRate": rate_row[col]
        })

interest_rate = pd.DataFrame(rates)
interest_rate["baseRate"] = pd.to_numeric(
    interest_rate["baseRate"], errors="coerce"
)

print(interest_rate.shape)
print(interest_rate.head())
print(interest_rate.tail())

(36, 2)
  yearMonth  baseRate
0   2023-01       3.5
1   2023-02       3.5
2   2023-03       3.5
3   2023-04       3.5
4   2023-05       3.5
   yearMonth  baseRate
31   2025-08       2.5
32   2025-09       2.5
33   2025-10       2.5
34   2025-11       2.5
35   2025-12       2.5

In [67]:
interest_rate.to_sql(
    "interest_rate",
    engine,
    if_exists="replace",
    index=False
)

print("MySQL interest_rate:", len(interest_rate))

MySQL interest_rate: 36

In [69]:
pop_2023 = pd.read_csv("../data/raw/LOCAL_PEOPLE_GU_2023.csv", encoding="cp949")
pop_2024 = pd.read_csv("../data/raw/LOCAL_PEOPLE_GU_2024.csv", encoding="utf-8")
pop_2025 = pd.read_csv("../data/raw/LOCAL_PEOPLE_GU_2025.csv", encoding="cp949")

seoul_pop = pd.concat(
    [pop_2023, pop_2024, pop_2025],
    ignore_index=True
)

print(seoul_pop.shape)
print(seoul_pop["stdr_de_id"].min())
print(seoul_pop["stdr_de_id"].max())

(656400, 65)
20240101.0
20251231.0

In [70]:
print(pop_2023.shape)
print(pop_2023.columns.tolist())
print(pop_2023.head(2))

(219000, 32)
['기준일ID', '시간대구분', '자치구코드', '총생활인구수', '남자0세부터9세생활인구수', '남자10세부터14세생활인구수', '남자15세부터19세생활인구수', '남자20세부터24세생활인구수', '남자25세부터29세생활인구수', '남자30세부터34세생활인구수', '남자35세부터39세생활인구수', '남자40세부터44세생활인구수', '남자45세부터49세생활인구수', '남자50세부터54세생활인구수', '남자55세부터59세생활인구수', '남자60세부터64세생활인구수', '남자65세부터69세생활인구수', '남자70세이상생활인구수', '여자0세부터9세생활인구수', '여자10세부터14세생활인구수', '여자15세부터19세생활인구수', '여자20세부터24세생활인구수', '여자25세부터29세생활인구수', '여자30세부터34세생활인구수', '여자35세부터39세생활인구수', '여자40세부터44세생활인구수', '여자45세부터49세생활인구수', '여자50세부터54세생활인구수', '여자55세부터59세생활인구수', '여자60세부터64세생활인구수', '여자65세부터69세생활인구수', '여자70세이상생활인구수']
      기준일ID  시간대구분  자치구코드       총생활인구수  남자0세부터9세생활인구수  남자10세부터14세생활인구수  \
0  20230101      0  11110  211983.7554      5256.3035        2985.2135
1  20230101      0  11140  161323.9236      5093.4474        1916.9721

   남자15세부터19세생활인구수  남자20세부터24세생활인구수  남자25세부터29세생활인구수  남자30세부터34세생활인구수  ...  \
0        5585.3388       10029.3603       10311.7458         8131.259  ...
1        2969.1968        6355.1874        7354.2686         6991.753  ...

   여자25세부터29세생활인구수  여자30세부터34세생활인구수  여자35세부터39세생활인구수  여자40세부터44세생활인구수  \
0        9989.7436        7420.0172        7877.9124         7403.790
1        8413.7271        6993.0188        7613.7788         5851.673

   여자45세부터49세생활인구수  여자50세부터54세생활인구수  여자55세부터59세생활인구수  여자60세부터64세생활인구수  \
0        8433.4562        7401.3378        7984.9511        6476.2241
1        5895.7675        5054.8313        5262.5790        4762.5191

   여자65세부터69세생활인구수  여자70세이상생활인구수
0        5176.6241    14109.9869
1        3330.8358     9806.8907

[2 rows x 32 columns]

In [71]:
print(pop_2025.shape)
print(pop_2025.columns[:5].tolist())

(217800, 33)
['stdr_de_id', 'tmzon_pd_se', 'adstrd_code_se', 'tot_lvpop_co', 'male_f0t9_lvpop_co']

In [72]:
pop_2023 = pop_2023.rename(columns={
    "기준일ID": "stdr_de_id",
    "자치구코드": "adstrd_code_se",
    "총생활인구수": "tot_lvpop_co"
})

pop_all = pd.concat([
    pop_2023[["stdr_de_id", "adstrd_code_se", "tot_lvpop_co"]],
    pop_2024[["stdr_de_id", "adstrd_code_se", "tot_lvpop_co"]],
    pop_2025[["stdr_de_id", "adstrd_code_se", "tot_lvpop_co"]]
], ignore_index=True)

print(pop_all.shape)
print(pop_all["stdr_de_id"].min())
print(pop_all["stdr_de_id"].max())

(656400, 3)
20230101
20251231

In [73]:
pop_all["yearMonth"] = (
    pop_all["stdr_de_id"].astype(str).str[:4]
    + "-"
    + pop_all["stdr_de_id"].astype(str).str[4:6]
)

code_to_gu = {int(code): name for name, code in seoul_gu.items()}

pop_all["guName"] = pop_all["adstrd_code_se"].map(code_to_gu)

living_pop = (
    pop_all
    .groupby(["guName", "yearMonth"])["tot_lvpop_co"]
    .mean()
    .reset_index()
    .rename(columns={"tot_lvpop_co": "avgLivingPop"})
)

print(living_pop.shape)
print(living_pop.head())

(900, 3)
  guName yearMonth   avgLivingPop
0    강남구   2023-01  796674.223998
1    강남구   2023-02  831518.858496
2    강남구   2023-03  823731.966718
3    강남구   2023-04  809914.335772
4    강남구   2023-05  807608.549482

In [74]:
living_pop.to_sql(
    "living_population",
    engine,
    if_exists="replace",
    index=False
)

print("MySQL living_population:", len(living_pop))

MySQL living_population: 900

In [75]:
ml_data = pd.read_sql("""
SELECT
    r.guName,
    r.yearMonth,
    r.contractCount,
    m.moveIn,
    m.moveOut,
    m.netMove,
    i.baseRate,
    l.avgLivingPop
FROM (
    SELECT
        guName,
        CONCAT(dealYear, '-', LPAD(dealMonth, 2, '0')) AS yearMonth,
        COUNT(*) AS contractCount
    FROM rental_transactions
    GROUP BY guName, dealYear, dealMonth
) r
JOIN migration m
    ON r.guName = m.guName
    AND r.yearMonth = m.yearMonth
JOIN interest_rate i
    ON r.yearMonth = i.yearMonth
JOIN living_population l
    ON r.guName = l.guName
    AND r.yearMonth = l.yearMonth
ORDER BY r.guName, r.yearMonth
""", engine)

print(ml_data.shape)
print(ml_data["yearMonth"].min())
print(ml_data["yearMonth"].max())
print(ml_data.isnull().sum())

(900, 8)
2023-01
2025-12
guName           0
yearMonth        0
contractCount    0
moveIn           0
moveOut          0
netMove          0
baseRate         0
avgLivingPop     0
dtype: int64

In [76]:
ml_data.to_sql(
    "ml_rent_market",
    engine,
    if_exists="replace",
    index=False
)

print("MySQL ml_rent_market:", len(ml_data))

MySQL ml_rent_market: 900